apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicolasgreskiv/pucpr-gh-pages:backend-latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: jdbc:mysql://database:3306/projdevsecops
        - name: DATABASE_USER
          value: user
        - name: DATABASE_PASSWORD
          value: senha
