apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicolasgreskiv/pucpr-gh-pages:backend-latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://database-service:3306/projdevsecops"  # Corrigido para usar o nome do serviço
        - name: SPRING_DATASOURCE_USERNAME
          value: "dbgrupo3"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "grupo3passtestetrocar123"
