apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8081
      nodePort: 30001  # Escolha uma porta disponível entre 30000-32767
  selector:
    app: backend
