apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3  # permite que até 3 pods fiquem indisponíveis durante a atualização
      maxSurge: 1        # permite que 1 pod adicional seja criado durante a atualização
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicolasgreskiv/pucpr-gh-pages:backend-latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://<database-service-name>:<database-port>/<database-name>"
        - name: SPRING_DATASOURCE_USERNAME
          value: "<username>"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "<password>"
