apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Alterar para LoadBalancer se for acessar de fora
  ports:
  - port: 8080
    targetPort: 8081  # Corrigido para o port do container
  selector:
    app: backend
