apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 1Gi  # Tamanho reduzido para 1GB
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/database  # Certifique-se de que este caminho existe no nรณ
