apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 5  # Alterado para 5 réplicas
  selector:
    matchLabels:
      app: database
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Permite que até 1 pod fique indisponível durante a atualização
      maxSurge: 1        # Permite que 1 pod adicional seja criado durante a atualização
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "grupo3rootpassteste123"
        - name: MYSQL_DATABASE
          value: "projdevsecops"
        - name: MYSQL_USER
          value: "dbgrupo3"
        - name: MYSQL_PASSWORD
          value: "grupo3passtestetrocar123"
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
