apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: "database-service"
  replicas: 1  # Mantendo apenas 1 réplica
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "grupo3rootpassteste123"
        - name: MYSQL_DATABASE
          value: "projdevsecops"
        - name: MYSQL_USER
          value: "dbgrupo3"
        - name: MYSQL_PASSWORD
          value: "grupo3passtestetrocar123"
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/mysql
  volumes:  # Adicionando a seção de volumes
  - name: database-storage
    persistentVolumeClaim:
      claimName: database-pvc  # Referenciando o PVC que você deseja usar
