apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 1Gi  # Capacidade ajustada para 1 GiB
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/database  # Mantenha isso para desenvolvimento
