apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # permite que até 3 pods fiquem indisponíveis durante a atualização
      maxSurge: 0        # permite que 1 pod adicional seja criado durante a atualização
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nicolasgreskiv/pucpr-gh-pages:frontend-latest
        ports:
        - containerPort: 80
